### ISSUE TITLE
Clarify and simplify

### ISSUE THREAD

**Issue by martinjanocko** [Amir-Naji/Discount#1]
Hello, I saw this repository and was wondering if we can simplify and clarify few things.

From the original assignment:
`result = (amount - (0.1m * amount)) - disc * (amount - (0.1m * amount));`
What is it actually calculating? Can we simplify this formula or make something more generic?

Also, what is the difference between `CommonCalculation` and `MoreComplicatedCommonCalculation`? What do they calculate?

Could we also improve the naming to be more concrete? What do things like `PercentCalculator`, `CommonCalculation`, `MoreComplicatedCommonCalculation` represent? To me this seems way too generic and does not help me understand the purpose of the code.

**Comment by Amir-Naji** [comment]
> Hello, I saw this repository and was wondering if we can simplify and clarify few things.
> 
> From the original assignment: `result = (amount - (0.1m * amount)) - disc * (amount - (0.1m * amount));` What is it actually calculating? Can we simplify this formula or make something more generic?
>
As far as I know it's a discount calculator. I think it calculates the actual value after discount applied.
> 
> Also, what is the difference between `CommonCalculation` and `MoreComplicatedCommonCalculation`? What do they calculate?
> 
I just want to show that it can  be done cleaner and easier via encapsulation and try to follow the SOLID principal. I wrote it in less than an hour so I didn't much of attention to small details!! 😆 
The first one calculate `(0.1m * amount)` short version and the second one calculate longer version `(amount - (0.1m * amount))`
> Could we also improve the naming to be more concrete? What do things like `PercentCalculator`, `CommonCalculation`, `MoreComplicatedCommonCalculation` represent? To me this seems way too generic and does not help me understand the purpose of the code.

Sure, I'll do that. I have an issue with naming. I should pay more attention!! 😅

**Comment by Amir-Naji** [comment]
@martinjanocko, not sure if I understood you by simplify the formula? 🤔 

If you mean have something like X - Y * Z then I guess it's possible. First I wanted to show how it is possible to follow the OO and SOLID principal.

**Comment by martinjanocko** [comment]
so, what i was thinking about, in a formula like this: `(amount - (0.1m * amount))` do we even need the `amount -` part? is there any difference in CommonCalculation and MoreComplicatedCommonCalculation if the percentage is 50% ie. 0.5m?

**Comment by Amir-Naji** [comment]
Your assumtion is correct if the percentage is 50%(we don't need it there and that's Tier 3 which uses the `(0.5m * amount)` alone, but if the the percentage is something else not sure removing the `amount` will help.

**Comment by Amir-Naji** [comment]
@martinjanocko I chenged the names I hope they are more clear now. 

Regarding the simplification there is another way to do that: 
since we know there won't be a discount more than 1 then we can basically reduce the amount from the value that is sent then we can simplify the calculation.

I mean if it sends 0.3 that means we want to have 30% discount then we can calculate the 70% of it then the rest should be the same, and it should have a same result.

**Comment by Amir-Naji** [comment]
Actually it won't work. I think the way that it is probably the most useful one. Unless the Discount input(0.1, 0.3, ...) get reversed then we can have one algorithm for all of them.

At the moment there are two ways it calculates one substract the discount `(amount - (0.1m * amount))` and without it. If instead of sending 0.7 to the Tier3 we send 0.3 then we can use the common calculation `(amount - (0.1m * amount))`, or we can use the remaining value instead and use the `(0.1m * amount)`.

0.1 => (amount - (0.1m * amount)) => 100 - (0.1 * 100) = 90
0.5 => (amount - (0.5m * amount)) => 100 - (0.5 * 100) = 50 (Which we can use `(0.1m * amount)`)
0.7 => (amount - (0.7m * amount)) => 100 - (0.7 * 100) = 30 (Which is wrong)

0.1 => (0.1m * amount) => (0.1 * 100) = 10 (Which is wrong)
0.5 => (0.5m * amount) => (0.5 * 100) = 50 (Which is exactly as  `(amount - (0.1m * amount))`)
0.7 => (0.7m * amount) => (0.7 * 100) = 70 

So I don't see any way that we can combine them in one, unless I use:
0.1 => 0.9 => (0.9m * amount) => (0.9 * 100) = 90 (Which is right now)
0.5 => (0.5m * amount) => (0.5 * 100) = 50 (Which is exactly as  `(amount - (0.1m * amount))`)
0.7 => (0.7m * amount) => (0.7 * 100) = 70

**Comment by martinjanocko** [comment]
considering the discount coefficients were hardcoded in the first place, I think changing them is not an issue if the outcome is the same and it enables us to have a more simple code.

**Comment by Amir-Naji** [comment]
My thinking was the input is not something that I can do anything about it and if the input is something clients get used to it then changing the input wouldn't be very reasonable. I was trying to change the code and not the input, in that case I think I can make it in a way that accept the dicount and returns the correct amount.

**Comment by martinjanocko** [comment]
but is the discount percentage an input? at least looking at the original Calculate method I don't think it is or was meant as such.

**Comment by Amir-Naji** [comment]
Hmm, that was my feeling that wanted to be like that!! 😆 
I thought the client gave the person those numbers and formula and he/she made that!! 😅

**Comment by Amir-Naji** [comment]
I changed some part of the code and changed some names I hope it is more clear now!!

**Comment by martinjanocko** [comment]
Thank you!

**Comment by Amir-Naji** [comment]
Thank you too. I just did the last changes that I thought I could do after the update the algorithm. When you asked about the cleaning the code I didn't expect to clean the algorithm itself as well!! I think there was a misunderstanding from my side.
